#!/bin/sh
rm -rf `find . -name CMakeFiles`
rm -rf `find . -name CMakeCache.txt`
rm -rf `find . -name Makefile`
rm -rf `find . -name cmake_install.cmake`
rm -rf `find . -name install_manifest.txt`
rm -rf `find . -name *.log`
rm -rf `find . -name _CPack_Packages`
rm -rf `find . -name CPackConfig.cmake`
rm -rf `find . -name CPackSourceConfig.cmake`