#include <vsx_module_static_factory.h>
#include <map>

// will fill out internal std::maps with pointers to factory functions
void vsx_module_static_factory::vsx_module_static_factory()
{
  #define SF_ADD_MODULE(name) module_names.push_back(name)

  // to be auto-generated by cmake
  SF_ADD_MODULE("math_basic");
}

// fake dlsym, returns function pointers to static functions
void *vsx_module_static_factory::dlsym(void *handle, const char *symbol)
{
  
}

std::list vsx_module_static_factory::get_factory_names()
{
  
}

void* vsx_module_static_factory::dlopen(const char *filename)
{
}